[bot]
user	    = "cvmBotJS" # Bot Username
ip          = "ws://127.0.0.1:6004" # Websocket VM Endpoint
origin	    = "https://computernewb.com"
prefix	    = "j?" # Command Prefix
vmid	    = "your-vm-id"

[login]
staffpw	    = "hunter2" # Admin / Mod Password
token	    = "your-token-here"

[settings]
login	    = "true" # Enable / Disable Login
startup	    = "false" # Toggle Bot sent message on every join
startupmsg  = "I have appeared as a bot!"

[developer]
debug       = "false" # Enable / Disable debugger
