[cvmbot]
ip				= "ws://127.0.0.1:6004"
vmname 			= "acoolvm"
username 		= "CoreBot-JS"
adminpass	 	= "hunter2"
ver		 		= "1.3.1-dev"
builddate 		= "2024-02-15 3.18pm +7"

[cvmcmd]
ask 			= "false"
help 			= "true"
test 			= "true"
xsstest 		= "false"

[dcbot]
prefix 			= "g!"
token 			= "insert-bot-token"
channel 		= "channel-id"
ver 			= "1.0.1-dev"
builddate		= "2024-02-15 3.18pm +7"