[cvmbot]
ip          = "ws://127.0.0.1:6009"
vmname	    = "acoolvm"
username    = "CoreBotJS"
adminpass   = "hunter2"
ver	    = "1.4.0-dev"
builddate   = "2024.12.10"
prefix      = "!"

[cvmcmd]
ask 		= "true"
help 		= "true"
test 		= "true"
xsstest 	= "true"